// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfwqqiejlfdamooagjbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtmd3FxaWVqbGZkYW1vb2FnamJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjA3NTUsImV4cCI6MjA3MjM5Njc1NX0.2bwevv6DC8THXiB9nHR3a7lc_SK648iE37R-nraxITw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});